# Generated by Django 5.2.17 on 2026-08-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Cn', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('driving_license_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturing_year', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=255)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'available'), ('reserved', 'reserved')], max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Pending', 'Pending')], max_length=255)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_date', models.DateField(auto_now_add=True)),
                ('damage_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('rental', models.ManyToManyField(to='vehicle_rental_system.rentals')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(auto_now_add=True)),
                ('maintenance_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress')], max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.vehicle')),
            ],
        ),
    ]
