# Generated by Django 5.2.17 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('allergies', models.CharField(default='None', max_length=255)),
                ('medical_history', models.CharField(default='None', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
