# Generated by Django 5.2.17 on 2026-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_clinic', '0002_medicalrecord_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('P', 'PAID'), ('U', 'UNPAID')], max_length=255)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
