# Generated by Django 5.2.17 on 2026-08-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=255, unique=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('ambulance_type', models.CharField(max_length=255)),
                ('ambulance_status', models.CharField(choices=[('A', 'Available'), ('B', 'Busy'), ('M', 'Maintenance')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('priority_status', models.CharField(choices=[('A', 'Low'), ('B', 'Medium'), ('C', 'High')], max_length=255)),
                ('request_time', models.DateTimeField()),
                ('request_status', models.CharField(choices=[('A', 'Pending'), ('B', 'Dispatch'), ('C', 'Completed')], max_length=255)),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance_service.ambulance')),
            ],
        ),
    ]
